#!/bin/bash
#Script para redimencionar imagenes al 50% para Nautilus
#
########## Declaro Variables ##########

#
########## Funciones ##########
#

#
########## Main ##########


########## Borro Temporales ##########
#

#
########## Fin Script ##########


